# Generated by Django 3.1.5 on 2021-01-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_exptlem', '0002_auto_20210116_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='isworking',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='tel',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
